
Vagrant.configure(2) do |config|

  config.vm.define "ansible" do |myconf1|
    myconf1.vm.box = "centos/7"
    myconf1.vm.hostname = 'fileserver.xxx.com'
    myconf1.vm.provision "shell", path: "ansible-deployment.sh"
    myconf1.vm.network "private_network", ip: "10.0.0.10",
      virtualbox__intnet: "public"
  end

 config.vm.define "centos1" do |myconf2|
    myconf2.vm.box = "centos/7"
    myconf2.vm.hostname = 'mail.xxx.com'
    myconf2.vm.provision "shell", path: "centos1-deployment.sh"
    myconf2.vm.network "private_network", ip: "10.0.0.11",
      virtualbox__intnet: "public"
  end

  config.vm.define "centos2" do |myconf3|
    myconf3.vm.box = "centos/7"
    myconf3.vm.hostname = 'database.xxx.com'
    myconf3.vm.provision "shell", path: "centos2-deployment.sh"
    myconf3.vm.network "private_network", ip: "10.0.0.12",
      virtualbox__intnet: "public"
  end

  config.vm.define "centos3" do |myconf4|
    myconf4.vm.box = "centos/7"
    myconf4.vm.hostname = 'web.xxx.com'
    myconf4.vm.provision "shell", path: "centos2-deployment.sh"
    myconf4.vm.network "private_network", ip: "10.0.0.13",
      virtualbox__intnet: "public"
  end 

end
