- hosts: centos1.example.com.local
  become: yes
  vars:
    mygroups:
      stupidmanagers:
        gid: 7777
        members:
          - user1
          - user2
          - user3
      ansibleadmins:
        gid: 8888
        members:
          - user10
          - user11
          - user12
      hackers:
        gid: 9999
        members:
          - user20
          - user21
          - user22
 tasks:
  - name: create groups
    group:
      name: "myuser{{item}}"
      state: present
    with_sequence: start=1 end=5
  - name: create users from 1 to 50
    user:
      name: "myuser{{item}}"
      state: present
      group: "myuser{{item}}"
    with_sequence: start=1 end=5

  - name: create groups from vars
    group:
      name: "{{item.key}}"
      gid: "{{item.value.gid}}"
      state: present
    with_dict: "{{mygroups}}"

  - name: modify group membership
    debug:
      msg="{{mygroups.value.members}}"
    with_dict: "{{mygroups}}"

