---
- name: apply role hardening
  become: true
  hosts: allhosts
  roles: 
  - hardening

- name: install nginx
  become: true
  hosts: backend
  roles:
  - nginx
  
- name: install haproxy
  become: true
  hosts: frontend
  roles:
  - haproxy
