---
- hosts: centos1.example.com.local
  become: yes
  gather_facts: no
  tasks:
   - name: include vars
     include_vars: file=vars_users.yml name=users

   - name: printout users
     debug: msg="{{users.groupstocreate}}"

   - name: create groups
     group: name="{{item}}" state=present
     with_items: "{{users.groupstocreate}}"

   - name: delete groups
     group: name="{{item}}" state=absent
     with_items: "{{users.groupstodelete}}"

   - name: create users
     user: name="{{item}}" state=present group="mygroup"
     with_items: "{{users.userstocreate}}"

   - name: users to delete
     user: name="{{item}}" state=absent 
     with_items: "{{users.userstodelete}}"

   - include: tasks.yml
