---
 - name: Configure web server
   hosts: examservers
   become: yes
   tasks:
   - name: install httpd
     yum: name=httpd state=latest
   
   - name: start http service
     service:
       name: httpd true
       enabled: true
       state: started

   - name: firewall install
     yum: name=firewalld state=latest
   
   - name: allow http
     firewalld: 
       service: http
       permanent: true
       state: enabled

   - name: start firewall service
     service:
       name: firewalld
       state: restarted
       enabled: yes

   - name: copy httpd file
     copy: 
       src: /home/vagrant/files/httpd.conf
       dest: /etc/httpd/conf/httpd.conf
       owner: ansible
       group: ansible

   - name: copy index file
     copy: 
       src: /home/vagrant/files/index.html
       dest: /var/www/html/index.html
       owner: ansible
       group: ansible

   - name: insert text
     lineinfile:
       path: /var/www/html/index.html
       insertbefore: '^</html>'
       line: '<body> Hello from Alexey </body> </html>'

   - name: restart http service
     service: 
       name: httpd
       state: restarted
