Vagrant.configure(2) do |config|

   config.vm.define "ansible" do |conf1|
   conf1.vm.box = "centos/7"
   conf1.vm.hostname = "ansible.example.com"
   conf1.vm.provision "shell", path: "ansible.sh", privileged: false
 end

   config.vm.define "centos" do |conf2| 
   conf2.vm.box = "centos/7"
   conf2.vm.hostname = "centos.example.com"
 end
 
   config.vm.define "ubuntu" do |conf3|
   conf3.vm.box = "yk0/ubuntu-xenial"
   conf3.vm.hostname = "ubuntu.example.com"
 end

end
