---
 - name: install epel-release
   yum: name=epel-release state=present

 - name: install nginx
   yum: name=nginx state=present
   

 - name: modify nginx configuration file
   template:
     src: nginx.conf.j2
     dest: /etc/nginx/nginx.conf

 - name: copy index file
   template: 
     src: index.html.j2
     dest: /usr/share/nginx/html/index.html
   notify: restart_nginx

 - name: permit http through firewall
   firewalld: service=http permanent=true state=enabled
   notify: restart_firewalld
