---
- hosts: all
  become: yes
  vars:
    backends:
      - ansible.example.com.local
    frontends:
      - centos1.example.com.local
      - centos2.example.com.local
  tasks:
  - name: install haproxy
    yum: name=haproxy state=present
    when: inventory_hostname in groups['backends']

  - name: modify haproxy configuration file
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    when: inventory_hostname in groups['backends']      
