---
- name: apply role hardening
  become: true
  hosts: allhosts
  roles:
  - { role: hardening, tags: hardening }

- name: appply role email
  become: true
  hosts: email
  roles:
  - { role: email, tags: email }


- name: apply role db
  become: true
  hosts: db
  roles:
  - { role: db, tags: db }

- name: apply role httpd
  become: true
  hosts: httpd
  roles:
  - { role: httpd, tags: httpd }

- name: apply role nfs
  become: true
  hosts: nfs
  roles:
  - { role: nfs, tags: nfs}

- name: apply role nfs_client
  become: true
  hosts: db, httpd
  roles:
  - { role: nfs_client, tags: nfs_client }
