---
 - name: install haproxy
   yum: name=haproxy state=present
   when: inventory_hostname in groups['frontends']

 - name: modify haproxy configuration file
   template:
     src: haproxy.cfg.j2
     dest: /etc/haproxy/haproxy.cfg
   notify: restart_haproxy
   when: inventory_hostname in groups['frontends']

 - name: debug
   debug:
     msg="{{inventory_hostname}}"
   when: inventory_hostname in groups['backends']
