---
- name: install nfs-utils
  yum:
    name: nfs-utils
    state: installed
    
- name: start nfs server
  service:
    name: nfs
    state: started
    enabled: true

- name: create share directory
  file:
    path: "{{ item.dir }}"
    state: directory
  with_items: "{{ nfs_share }}"

- name: configure nfs
  template:
    src: exports.conf.j2
    dest: /etc/exports
  notify: read config 

