
Vagrant.configure(2) do |config|

  config.vm.define "ansible" do |myconf1|
    myconf1.vm.box = "centos/7"
    myconf1.vm.hostname = 'ansible.example.com'
    myconf1.vm.provision "shell", path: "centos-deployment.sh", privileged: false
    myconf1.vm.network "private_network", ip: "10.0.0.1",
      virtualbox__intnet: "ansible"
  end

 config.vm.define "centos" do |myconf2|
    myconf2.vm.box = "centos/7"
    myconf2.vm.hostname = 'centos.example.com'
  end

  config.vm.define "ubuntu" do |conf|
    conf.vm.box = "ubuntu/xenial64"
    conf.vm.hostname = 'ubuntu.example.com'
  end

  config.vm.define "vsrx1" do |vsrx1|
    vsrx1.vm.box = "juniper/ffp-12.1X47-D15.4"
    vsrx1.vm.hostname="vsrx1"
  end

end
