---
 - name: install firewalld
   yum: name=firewalld state=present
   notify: firewall_enable

 - name: firewalld permit ssh
   firewalld: service=ssh source={{source_network}} permanent=true state=enabled   
   notify: firewalld_reload

 - name: disable selinux
   selinux: state=disabled

 - name: copy hosts file
   template:
     src: hosts.j2
     dest: /etc/hosts

 - name: configure dns server
   template:
     src: resolv.conf.j2
     dest: /etc/resolv.conf
   notify: restart_network
