---
- name: install postfix
  yum:
    name: postfix
    state: present

- name: start postfix
  service:
    name: postfix
    state: started
    enabled: true

- name: copy main.cf file
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
  notify: restart postfix
