Vagrant.configure(2) do |config|
 
  config.vm.define "ansible" do |dos|
    dos.vm.box = "centos/7"
    dos.vm.hostname = 'ansible.example.com'
    dos.vm.network "private_network", ip: "172.28.128.20"
    dos.vm.provision "shell", inline: $upeth1
    dos.vm.provision "shell", inline: <<-SHELL
      sudo useradd ansibleadmin -m
      sudo echo "Ansible123" | passwd "ansibleadmin" --stdin
      sudo yum install -y epel-release
      sudo yum install -y ansible
      sudo yum install -y git
      sudo cp /vagrant/sshd_config /etc/ssh/sshd_confi
      sudo cp /vagrant/ansible.inventory /var/ansible.inventory
      sudo cp /vagrant/ansible.cfg /home/ansibleadmin/
      sudo cp /vagrant/sshd_config /etc/ssh/sshd_config
      sudo cp /vagrant/runme.sh /home/vagrant/runme.sh
      sudo cp /vagrant/ansibleadmin /etc/sudoers.d/ansibleadmin
      sudo systemctl restart sshd
    SHELL
  end
 
  config.vm.define "centos" do |dos|
    dos.vm.box = "centos/7"
    dos.vm.hostname = 'centos.exmample.com'
    dos.vm.network "private_network", ip: "172.28.128.21"
    dos.vm.provision "shell", inline: $upeth1
    dos.vm.provision "shell", inline: <<-SHELL
      sudo useradd myuser -m
      sudo echo "Ansible123" | passwd "myuser" --stdin
      sudo useradd ansible -m
      sudo echo "Ansible123" | passwd "ansible" --stdin
      sudo yum install -y epel-release
      sudo yum install -y ansible
      sudo yum install -y git
      sudo cp /vagrant/sshd_config /etc/ssh/sshd_config
      sudo cp /vagrant/myuser /etc/sudoers.d/myuser
      sudo systemctl restart sshd
    SHELL
  end
 
end

$upeth1 = <<SCRIPT
sudo ifup eth1
sleep 5
sudo ip a s
SCRIPT
