---
- name: Loop lab
  hosts: examservers
  become: true
  vars:
    mygroups:
      stupidmanagers:
        gid: 7777
        members:
          - myuser1
          - myuser11
          - myuser12
      ansibleadmins:
        gid: 8888
        members:
          - myuser10
          - myuser11
          - myuser12
      hackers:
        gid: 9999
        members:
          - myuser20
          - myuser21
          - myuser22
  tasks:
    - name: create users
      user:
        name: "{{ item }}"
        state: present
      with_sequence: start=1 end=50 format=myuser%d

    - name: create groups
      group:
        name: "{{ item.key }}"
        gid: "{{ item.value.gid }}"
      with_dict: "{{ mygroups }}"
    
    - name: change group membership
      include: inner.yml
      with_dict: "{{ mygroups }}"
      loop_control:
        loop_var: outer_item
