---
 - hosts: all
   become: yes
   roles:
   - hardening

 - hosts: email
   become: yes
   roles:
   - email

 - hosts: mariadb
   become: yes
   roles:
   - mariadb

 - hosts: http
   become: yes
   roles:
   - http

 - hosts: nfs
   become: yes
   roles:
   - nfs
