Vagrant.configure(2) do |config|

  config.vm.define "ansible" do |myconf|
    myconf.vm.box = "centos/7"
    myconf.vm.hostname = 'ansible.example.com'
  end

 config.vm.define "centos" do |myconf|
    myconf.vm.box = "centos/7"
    myconf.vm.hostname = 'centos.example.com'
  end

  config.vm.define "ubunty" do |conf|
    conf.vm.box = "ubuntu/xenial64"
    conf.vm.hostname = 'ubuntu.example.com'
  end

end
