---
- name: Install a service on multiple systems
  become: true
  hosts: group1, group2
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: installed

    - name: start httpd
      service:
        name: httpd
        state: started

    - name: copy httpd.conf
      get_url:
        url: http://ansible.example.com/httpd.conf.template
        dest: /etc/httpd/conf/httpd.conf
        mode: 0644
      notify: restart httpd

    - name: modify index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "Hello from {{ ansible_hostname }}"
        insertafter: 'EOF'
        create: yes
      notify: restart httpd

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted

