---
- name: turn on httpd
  become: true
  hosts: allservers
  tasks:
    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: true

    - name: allow http and https
      firewalld:
        service: "{{ item }}"
        state: enabled
        immediate: true
        permanent: true
      with_items:
        - http
        - https
